language: php

php:
  - 7.0

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction --dev

script: phpunit --coverage-clover=coverage.xml

after_script:
  - if [ -f coverage.xml ]; then wget https://scrutinizer-ci.com/ocular.phar; fi
  - if [ -f coverage.xml ]; then php ocular.phar code-coverage:upload --format=php-clover ./coverage.xml; fi